on:
  push:
  pull_request:
    paths:
      - "**.json"
      - "**.js"
      - "**.ts"
      - "**.yml"
      - "**.yaml"
      - "**.rs"
      - "**.md"
permissions:
  packages: read
  contents: read
name: check-typos
jobs:
  check-typos:
    name: check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3
      - name: Install codespell
        run: |
            uv venv .venv
            echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
            echo "$PWD/.venv/bin" >> $GITHUB_PATH
            uv pip install codespell
      - name: Run codespell
        run: codespell --config .codespellrc # Edit this file to tweak the typo list and other configuration.
